Check for Slava: filter category
greedWizard/adservertest pull request #1
Opened 2022-07-05 12:16 UTC by FalseHuman

Для фильтрации использовался django-mptt. Его нужно накатить pip install django-mptt

2022-07-06 06:49 UTC, greedWizard requested changes

2022-07-06 06:49 UTC, greedWizard commented on adserver/board/views.py
> +            for category in categories:
На такие случаи есть ```.values_list('id', flat=True)```, чтобы не плодить циклы

2022-07-06 06:49 UTC, greedWizard commented on adserver/board/views.py
> +            #ads = ads.filter(category__id=get_data['category'])
Удали эту строчку, она больше не понадобится

2022-07-06 09:09 UTC, FalseHuman commented
Исправил теперь работает, так как нам нужно, так же исправил вывод всех категорий, теперь они выводятся в древовидном порядке - это видно на 1 скриншоте + в админке тоже вывод в древовидной структуре 2 скриншот (https://disk.yandex.ru/a/RRTqW3smLqLJkg)

2022-07-07 09:59 UTC, FalseHuman commented
Переписал Ads View с использованием generics и django-filters.

2022-07-15 19:04 UTC, merged